Chore/contributing guidelines
americanexpress/lumberjack pull request #5
Opened 2020-01-31 12:30 UTC by nellyk

2020-02-05 22:43 UTC, mtomcal requested changes

2020-02-05 22:43 UTC, mtomcal commented on CONTRIBUTING.md
> +Runs linting on the current branch and checks that the commits follow [conventional commits](https://www.conventionalcommits.org/)
```suggestion
Runs linting on the current branch and verifies that the `package-lock.json` file includes public NPM registry URLs.
```

2020-02-05 22:43 UTC, mtomcal requested changes

2020-02-05 22:43 UTC, mtomcal commented on CONTRIBUTING.md
> +    $ cd npm install
```suggestion
    $ npm install
```

2020-02-07 22:16 UTC, 10xLaCroixDrinker submitted a review, later dismissed

2020-02-11 22:21 UTC, JAdshead submitted a review, later dismissed

2020-02-12 17:00 UTC, JamesSingleton submitted a review, later dismissed

2020-02-17 17:48 UTC, mtomcal requested changes

2020-02-17 17:48 UTC, mtomcal commented on CONTRIBUTING.md
> +- Node version:[e.g 10.15.1]
OS?

2020-02-24 15:55 UTC, 10xLaCroixDrinker approved these changes

2020-02-24 17:55 UTC, mtomcal approved these changes

2020-02-25 18:29 UTC, merged